apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kafka-connect-secret-provider-class
  namespace: {{ .Values.namespace |  default "default" }}
spec:
  provider: oci
  secretObjects:
    - secretName: kafka-connect-secret
      type: Opaque
      data:
        - key: username
          objectName: kafka-connect-username
        - key: password
          objectName: kafka-connect-password
  parameters:
    secrets: |
      - name: kafka-connect-username
      - name: kafka-connect-password
    vaultId: {{ .Values.vault_id }}
    authType: instance
