apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ocir-secret-provider-class
  namespace: {{ .Values.namespace |  default "default" }}
spec:
  provider: oci
  secretObjects:
    - secretName: ocir-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - key: .dockerconfigjson
          objectName: dockerconfigjson
  parameters:
    secrets: |
      - name: dockerconfigjson
    vaultId: {{ .Values.vault_id }}
    authType: instance
