{
 "title": "OCI Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "README", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Observability for OCI\n\n## Metrics\n\nOCI の [Grafana Plugin - Oracle Cloud Infrastructure Metrics](https://grafana.com/grafana/plugins/oci-metrics-datasource/) を用いて、以下のサービスの Metrics を可視化しています。\n\n- OKE\n- Compute\n- Load Balancer\n- API Gateway\n- Application Performance Monitoring - Monitoring\n- Application Performance Monitoring - Real User Monitoring\n- Autonomous Database\n\n## Tracing\n\nOCI APM を用いて分散トレーシングの情報を可視化しています。\n\n- [トレース・エクスプローラー](https://cloud.oracle.com/apm/apm-traces/traceList?apmDomain=ocid1.apmdomain.oc1.phx.amaaaaaassl65iqa52zu74k3oqxvfut2wk2ectmfafgjvnt5pmd6ouwvdkpq&apmTime=last_15_minutes&apmFilter=c2hvdyAodHJhY2VzKSBUcmFjZVN0YXR1cyBhcyBTdGF0dXMsCiAgICBUcmFjZUZpcnN0U3BhblN0YXJ0VGltZSBhcyAiU3RhcnQgVGltZSIsCiAgICBTZXJ2aWNlTmFtZSBhcyBTZXJ2aWNlLAogICAgT3BlcmF0aW9uTmFtZSBhcyBPcGVyYXRpb24sCiAgICBUcmFjZUR1cmF0aW9uIGFzIER1cmF0aW9uLAogICAgc3Bhbl9zdW1tYXJ5KCkgYXMgU3BhbnMsCiAgICBFcnJvckNvdW50IGFzICJTcGFuIEVycm9ycyIKICB3aGVyZSAoQXBtcnVtUGFnZVVwZGF0ZVR5cGU8PidDbGljaycgb3IgQXBtcnVtUGFnZVVwZGF0ZVR5cGUgaXMgb21pdHRlZCkKICBvcmRlciBieSBUcmFjZUZpcnN0U3BhblN0YXJ0VGltZSBkZXNj&region=us-phoenix-1)\n\n## Logging\n\n各 Worker Node の `/var/log/containers/*` に出力されるログをカスタム・ログとして収集し、OCI Logging で確認することができます。"
   }
  },
  { "title": "OKE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Node State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "NodeState",
     "namespace": "oci_oke",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Node Condition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 16 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "KubernetesNodeCondition",
     "namespace": "oci_oke",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Unschedulable Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "UnschedulablePods",
     "namespace": "oci_oke",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "K8s API Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "APIServerRequestCount",
     "namespace": "oci_oke",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "K8s API Server Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "APIServerResponseCount",
     "namespace": "oci_oke",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  { "title": "Compute (OKE Worker Nodes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "CpuUtilization",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Memoty Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "MemoryUtilization",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "LoadAverage",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Network IO - IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "NetworksBytesIn",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Network IO - OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "NetworksBytesOut",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Disk IO - Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "DiskBytesRead",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Disk IO - Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "DiskBytesWritten",
     "namespace": "oci_computeagent",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Application Performance Monitoring - Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "Process CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "ProcessCpuLoad",
     "namespace": "oracle_apm_monitoring",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "System CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "SystemCpuLoad",
     "namespace": "oracle_apm_monitoring",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "HeapUsed",
     "namespace": "oracle_apm_monitoring",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "System Physical Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "SystemPhysicalMemoryFree",
     "namespace": "oracle_apm_monitoring",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Total Trace Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "TotalTraceCount",
     "namespace": "oracle_apm_monitoring",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Total Span Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "TotalSpanCount",
     "namespace": "oracle_apm_monitoring",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Application Performance Monitoring - Real User Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "Page Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "PageViews",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Frustrated Page Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "FrustratedPageViews",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Page Render Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "PageRenderTime",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Active Sessions per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "ActiveSessionsPerMin",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Connect Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "ConnectCount",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Ajax Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "ApdexScore",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Ajax Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "AjaxCalls",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Ajax Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "AjaxErrors",
     "namespace": "oracle_apm_rum",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Load Balancer (Kubernetes Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "ActiveConnections",
     "namespace": "oci_lbaas",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Peak Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "PeakBandwidth",
     "namespace": "oci_lbaas",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "HttpRequests",
     "namespace": "oci_lbaas",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "BytesReceived",
     "namespace": "oci_lbaas",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "BytesSent",
     "namespace": "oci_lbaas",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "HttpRequests",
     "namespace": "oci_apigateway",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Http Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "HttpResponses",
     "namespace": "oci_apigateway",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 117 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "BytesSent",
     "namespace": "oci_apigateway",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 117 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "BytesReceived",
     "namespace": "oci_apigateway",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 117 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "Latency",
     "namespace": "oci_apigateway",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  { "title": "Autonomous Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "CpuUtilization",
     "namespace": "oci_autonomous_database",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "StorageUtilization",
     "namespace": "oci_autonomous_database",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Database Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 134 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "DatabaseAvailability",
     "namespace": "oci_autonomous_database",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Current Logons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 134 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "CurrentLogons",
     "namespace": "oci_autonomous_database",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 134 },
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "ocid1.compartment.oc1..aaaaaaaaiwbdcl4r4aht6qhovvxi2kzphxoojzm7x7p2aml47egef24w4kyq",
     "metric": "StorageUsed",
     "namespace": "oci_autonomous_database",
     "region": "us-phoenix-1",
     "resolution": "auto",
     "resourcegroup": "select resource group",
     "tenancy": "select tenancy",
     "tenancymode": "single",
     "window": "auto"
    }
   ]
  }
 ]
}