FROM node:18-alpine as build-vue
ARG APM_PUBLIC_DATA_KEY
ARG APM_DATA_UPLOAD_ENDPOINT
WORKDIR /frontend
COPY front-vue .
RUN sed -i -e "s@__APM_DATA_UPLOAD_ENDPOINT__@${APM_DATA_UPLOAD_ENDPOINT}@g" public/index.html
RUN sed -i -e "s@__APM_DATA_UPLOAD_ENDPOINT__@${APM_DATA_UPLOAD_ENDPOINT}@g" public/index.html
RUN sed -i -e "s/__APM_PUBLIC_DATA_KEY__/${APM_PUBLIC_DATA_KEY}/g" public/index.html
RUN npm install && npm run build

FROM maven:3.9.0-eclipse-temurin-17 as build-helidon
WORKDIR /frontend
ADD front-helidon/src src
ADD front-helidon/pom.xml .
RUN ls -sal
RUN ls -sal ./src/main

COPY --from=build-vue /frontend/dist src/main/resources/static/
RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre-alpine
ARG APM_PRIVATE_DATA_KEY
ARG APM_DATA_UPLOAD_ENDPOINT
WORKDIR /frontend
COPY --from=build-helidon /frontend/target/front-helidon.jar .
COPY --from=build-helidon /frontend/target/libs ./libs
EXPOSE 8080
ENV tracing_service="frontend_helidon"
ENV tracing_data_upload_endpoint=${APM_DATA_UPLOAD_ENDPOINT}
ENV tracing_private_data_key=${APM_PRIVATE_DATA_KEY}

ENTRYPOINT ["java", "-jar", "front-helidon.jar"]


