apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oauth-secret-provider
  namespace: frontend
spec:
  provider: oci
  secretObjects:
    - secretName: oauth-secret
      type: Opaque
      data:
        - key: backendUrlBase
          objectName: oauth.backendUrlBase
        - key: backendUrl
          objectName: oauth.backendUrl
        - key: clientId
          objectName: oauth.clientId
        - key: clientSecret
          objectName: oauth.clientSecret
        - key: scope
          objectName: oauth.scope
        - key: oauthUrl
          objectName: oauth.tokenEndpoint
  parameters:
    secrets: |
      - name: oauth.backendUrlBase
        stage: CURRENT
      - name: oauth.backendUrl
        stage: CURRENT
      - name: oauth.clientId
        stage: CURRENT
      - name: oauth.clientSecret
        stage: CURRENT
      - name: oauth.scope
        stage: CURRENT
      - name: oauth.tokenEndpoint
        stage: CURRENT
    vaultId: ocid1.vault.oc1.phx.bzsb2orbaaeog.abyhqljrpizmuqhthuqm6vom4mlk5ybzw6a3js52f22clqj2ekohd6corjaa
    authType: instance
