apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ocir-secret-provider
  namespace: frontend
spec:
  provider: oci
  secretObjects:
    - secretName: ocir-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - key: .dockerconfigjson
          objectName: dockerconfigjson
  parameters:
    secrets: |
      - name: dockerconfigjson
    vaultId: ocid1.vault.oc1.phx.bzsb2orbaaeog.abyhqljrpizmuqhthuqm6vom4mlk5ybzw6a3js52f22clqj2ekohd6corjaa
    authType: instance
