apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: apm-secret-provider
  namespace: backend
spec:
  provider: oci
  secretObjects:
    - secretName: apm-secret
      type: Opaque
      data:
        - key: privateKey
          objectName: apm.private-data-key
        - key: dataUploadEndpoint
          objectName: apm.data-upload-endpoint
  parameters:
    secrets: |
      - name: apm.private-data-key
        stage: CURRENT
      - name: apm.data-upload-endpoint
        stage: CURRENT
    vaultId: ocid1.vault.oc1.phx.bzsb2orbaaeog.abyhqljrpizmuqhthuqm6vom4mlk5ybzw6a3js52f22clqj2ekohd6corjaa
    authType: instance
