apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datasource-secret-provider
  namespace: backend
spec:
  provider: oci
  secretObjects:
    - secretName: datasource-secret
      type: Opaque
      data:
        - key: url
          objectName: datasource.url
        - key: username
          objectName: datasource.username
        - key: password
          objectName: datasource.password
  parameters:
    secrets: |
      - name: datasource.url
        stage: CURRENT
      - name: datasource.username
        stage: CURRENT
      - name: datasource.password
        stage: CURRENT
    vaultId: ocid1.vault.oc1.phx.bzsb2orbaaeog.abyhqljrpizmuqhthuqm6vom4mlk5ybzw6a3js52f22clqj2ekohd6corjaa
    authType: instance
