server:
  # port: 8080
  # location on classpath (e.g. src/main/resources/WEB in maven)
  static.classpath:
    location: "/static"
    # this is optional, defaults to "/"
    #context: "/"
    welcome: "index.html"